# Generated by Django 4.1.3 on 2022-12-12 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0003_alter_after_options_alter_before_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='after',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='before',
        ),
        migrations.DeleteModel(
            name='After',
        ),
        migrations.DeleteModel(
            name='Before',
        ),
    ]
