# Generated by Django 4.1.3 on 2022-12-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0004_remove_worker_after_remove_worker_before_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
